# Henri Simmons, 22422504 - Operating Systems Project 1
# adapted from sample makefile in project spec
# ca216/myshell

myshell: myshell.c utility.c myshell.h
	gcc -Wall myshell.c utility.c -o myshell